Added CreateDeleteResponse to ResultHandler, Refactored GET, POST and DELETE response methods
retaildevcrews/loderunner pull request #173
Opened 2022-03-02 19:34 UTC by PurpleBriar

# Type of PR

- [ ] Documentation changes
- [x] Code changes
- [ ] Test changes
- [ ] CI-CD changes
- [ ] GitHub Template changes

## PR Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] My code follows the code style of this project.
- [x] I ran lint checks locally prior to submission.
- [x] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Purpose of PR

- Added CreateDeleteResponse to ResultHandler
- Refactored GET, POST and DELETE response methods

## Does this introduce a breaking change

- [ ] YES
- [x] NO

## Validation

- [x] Unit tests updated and ran successfully
- [x] Update documentation or issue referenced above

## Issues Closed or Referenced

- Closes #issue_number (this will automatically close the issue when the PR closes)
- References retaildevcrews/wcnp/issues/581

2022-03-02 20:01 UTC, gortegaMS requested changes

2022-03-02 20:01 UTC, gortegaMS commented on src/LodeRunner.API/src/Handlers/ResultHandler.cs
>                  logger.LogError(new EventId((int)HttpStatusCode.InternalServerError, $"{methodName} > {nameof(CreatePutResponse)}"), ex, "Exception");
Should we have local variable here as well?

2022-03-02 20:38 UTC, PurpleBriar commented on src/LodeRunner.API/src/Controllers/TestRunsController.cs
> +        private bool CanTestRunBeDeleted(TestRun testRun)
Updated to a static method

2022-03-02 20:38 UTC, PurpleBriar commented on src/LodeRunner.API/src/Handlers/ResultHandler.cs
> +            return await TryCatchException(logger, $"{methodName} > {nameof(CreateGetByIdResponse)}", async () =>
Added a local variable

2022-03-03 18:53 UTC, jofultz requested changes
Checks failed.

2022-03-03 22:27 UTC, gortegaMS approved these changes

2022-03-04 15:52 UTC, jofultz approved these changes

2022-03-04 15:57 UTC, joheec approved these changes

2022-03-04 15:58 UTC, merged