Loderunner checkov yaml fixes
retaildevcrews/loderunner pull request #224
Opened 2022-05-06 16:17 UTC by AAkindele

# Type of PR

- [ ] Documentation changes
- [x] Code changes
- [ ] Test changes
- [ ] CI-CD changes
- [ ] GitHub Template changes

## PR Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My code follows the code style of this project.
- [ ] I ran lint checks locally prior to submission.
- [ ] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Purpose of PR

- Fix checkov yaml issues in loderunner deployment template.

## Does this introduce a breaking change

- [ ] YES
- [x] NO

## Validation

- [ ] Unit tests updated and ran successfully
- [ ] Update documentation or issue referenced above

## Issues Closed or Referenced

2022-05-10 17:47 UTC, kforeverisback commented
We tested the access policy of emptyDir and found that its strictly tied to each pod instance.
See [this description](https://github.com/retaildevcrews/ngsa-app/pull/101) for details

2022-05-11 19:03 UTC, sivamu requested changes
Can we test the YAML changes in the dev environment before deploying to preprod?

2022-05-11 19:09 UTC, sivamu commented
I think the equivalent LR yaml file in the dev environment is: https://github.com/retaildevcrews/loderunner/blob/main/autogitops/dev/loderunner-commandmode.yaml

2022-05-11 19:51 UTC, AAkindele commented on autogitops/preprod/loderunner.yaml
> +          livenessProbe:
I double checked and there is no healthz for loderunner in command mode.

2022-05-11 20:02 UTC, merged