updated instructions to run integration tests in CodeSpaces
retaildevcrews/loderunner pull request #271
Opened 2022-07-14 18:44 UTC by PurpleBriar

# Type of PR

- [x] Documentation changes
- [ ] Code changes
- [ ] Test changes
- [ ] CI-CD changes
- [ ] GitHub Template changes

## PR Checklist

- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My code follows the code style of this project.
- [ ] I ran lint checks locally prior to submission.
- [ ] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Purpose of PR

Updated instructions to run integration tests in CodeSpaces

## Does this introduce a breaking change

- [ ] YES
- [x] NO

## Validation

- [ ] Unit tests updated and ran successfully
- [x] Update documentation or issue referenced above

## Issues Closed or Referenced

- Closes retaildevcrews/wcnp/issues/890

2022-07-21 18:54 UTC, jofultz commented on README.md
> +
We should be using the "test" CosmosDB for integration tests.  The name is [ngsa-asb-test-cosmos](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/648dcb5a-de1e-48b2-af6b-fe6ef28d355c/resourceGroups/rg-ngsa-asb-test-cosmos/providers/Microsoft.DocumentDB/databaseAccounts/ngsa-asb-test-cosmos)

2022-07-21 18:54 UTC, jofultz commented on README.md
> +echo $(eval az cosmosdb keys list -n ngsa-asb-dev-cosmos -g rg-ngsa-asb-dev-cosmos --query primaryMasterKey -o tsv) > secrets/CosmosKey
Same as previous.

2022-07-21 18:55 UTC, jofultz requested changes
Need to use a different CosmosDB instance.  See review comments.

2022-07-22 19:54 UTC, AAkindele approved these changes

2022-07-25 14:33 UTC, jofultz approved these changes

2022-07-25 14:33 UTC, merged