Fix Loderunner issues found by Grype scan
retaildevcrews/loderunner pull request #314
Opened 2022-11-04 23:00 UTC by AAkindele

# Type of PR

- [ ] Documentation changes
- [x] Code changes
- [ ] Test changes
- [x] CI-CD changes
- [ ] GitHub Template changes

## PR Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] My code follows the code style of this project.
- [x] I ran lint checks locally prior to submission.
- [x] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Purpose of PR

- Fix dotnet CVEs by upgrading Microsoft.Azure.Cosmos from 3.27.1 to 3.31.1
  - Actual issues is a dependency on System.Drawing.Common
- Fix curl CVEs by upgrading apk packages in Dockerfile base off nginx

## Does this introduce a breaking change

- [ ] YES
- [x] NO

## Validation

- [x] Unit tests updated and ran successfully
- [ ] Update documentation or issue referenced above

## Issues Closed or Referenced

- Closes https://github.com/retaildevcrews/wcnp/issues/1059

2022-11-04 23:05 UTC, AAkindele commented on src/LodeRunner.UI/Dockerfile
> +RUN apk update && apk upgrade
Some alternatives if we don't want to upgrade everything. At this time, both alternatives below end up installing the same version. But that could change in the future.

Upgrade only failing packages to specific version
```dockerfile
RUN apk add --no-cache \
  curl=7.83.1-r4 \
  libcurl=7.83.1-r4
```
Upgrade only failing packages to latest available version
```dockerfile
RUN apk upgrade curl libcurl
```

2022-11-04 23:50 UTC, AAkindele commented on src/LodeRunner.UI/Dockerfile
> +RUN apk update && apk upgrade
Checkov did not like `RUN apk update && apk upgrade` and `RUN apk upgrade curl libcurl`.
Adding a specific version pass both Grype and Checkov scans.

2022-11-07 14:14 UTC, gortegaMS requested changes
Just requested changes so we can discuss, I do have a couple questions

2022-11-07 16:46 UTC, PurpleBriar approved these changes

2022-11-07 18:55 UTC, merged